#!/bin/bash

JAR=$(ls target/scala-2.11/sparkrdf-?.?.jar | sort -r | head -1)

pushd tmp
spark-shell \
	--master local[*] \
 	--name "SparkRDF" \
 	--driver-memory 4g \
 	--jars ../$JAR \
 	--packages "org.apache.jena:jena-arq:2.13.0"
popd
